[tools]
deno = "latest"

[settings]
experimental = true

[hooks]
postinstall = "deno install"

[tasks.build]
run = "deno run -A npm:typescript/tsc && deno run -A npm:vite build"

[tasks.dev]
run = "deno run -A npm:vite"

[tasks.preview]
run = "deno run -A npm:vite preview"
